version: '3.8'

services:
  rag-app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8080:8000"
    command: python -m main
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-local
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "langchain"]
      interval: 10s
      timeout: 5s
      retries: 5
